baseurl = "https://blog.bishbashboshdesigns.co.uk/"
copyright = "All rights reserved"
languagecode = "en-US"
paginate = 10
pluralizelisttitles = false
title = "The Ramblings of a Front-End Developer"

# Disqus
disqusshortname = "boshdesigns"

# Set theme
theme = "casper"

  # Main Menu
  [[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 100
  [[menu.main]]
  name = "Portfolio"
  url = "http://www.bishbashboshdesigns.co.uk"
  weight = 101
  [[menu.main]]
  name = "Github"
  url = "https://github.com/boshdesigns"
  weight = 102
  [[menu.main]]
  name = "My Twitter"
  url = "https://twitter.com/shinyash"
  weight = 103
  [[menu.main]]
  name = "My LinkedIn"
  url = "https://uk.linkedin.com/in/ash-holley-03755851"
  weight = 104
  [[menu.main]]
  name = "JSFiddle"
  url = "https://jsfiddle.net/user/shinyash/"
  weight = 105


  [params]
  # author vars
  author = "shinyash"
  authorlocation = "Brighton, England"
  authorwebsite = "http://www.bishbashboshdesigns.co.uk/"
  bio = "Drupal Front-End Developer with a small gaming addiction"

  # homepage
  cover = "images/cover_polenord.jpg"
  description = ""

  logo = "images/logo.png"

  # Social icons
  githubName = "boshdesigns"
  twitterName = "shinyash"
  #instagramName = "iamashholley"
  linkedinName = "ash-holley-03755851"

  # footer
  hideHUGOSupport = false
  googleAnalyticsUserID = "UA-100707687-1"

  [permalinks]
  post = "/:slug/"

  [sitemap]
  ChangeFreq = ""
  Filename = "sitemap.xml"
  Priority = "-1"
